// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/deep-dive/MonthlyDeepDive.tsx": () => import("../components/mockups/deep-dive/MonthlyDeepDive.tsx"),
  "./components/mockups/food-snap/AdviceState.tsx": () => import("../components/mockups/food-snap/AdviceState.tsx"),
  "./components/mockups/food-snap/ReviewState.tsx": () => import("../components/mockups/food-snap/ReviewState.tsx"),
  "./components/mockups/home/HomeTired.tsx": () => import("../components/mockups/home/HomeTired.tsx")
};
